# Generated by Django 4.1.3 on 2023-09-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad-Soyad')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=120, null=True, verbose_name='Konu')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mesaj')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Başlığı')),
                ('description', models.TextField(verbose_name='Açıklaması')),
                ('image', models.ImageField(upload_to='', verbose_name='Fotoğrafı')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad-Soyad')),
                ('twitter_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter Link')),
                ('facebook_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook Link')),
                ('instagram_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='İnstagram Link')),
                ('linkedin_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Linked-in Link')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad-Soyad')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şirket')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mesaj')),
            ],
        ),
    ]
