# Generated by Django 4.1.3 on 2023-09-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uluocakapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meslek'),
        ),
    ]
