# Generated by Django 4.1.3 on 2023-09-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uluocakapp', '0002_team_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fotoğrafı'),
        ),
    ]
